project1_schedule/schedule_app/config/routes.rb
ScheduleApp::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :sessions
  get "/logout", to: "sessions#destroy"
  
  resources :users do 
    collection {post :search, to: 'users#search'}
  end 

  resources :courses

  resources :classrooms

  resources :locations
  

  get "/events/:id", to: "courses#show"

   
  
  root :to => 'locations#index'

end

project1_schedule/schedule_app/app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :maxpeople, :name, :location_id

has_many :courses
has_many :users, through: :courses
belongs_to :location

end

project1_schedule/schedule_app/app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  # GET /classrooms
  # GET /classrooms.json
  authorize_resource
  
  def index
    @classrooms = Classroom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
    end
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classroom }
    end
  end

  # GET /classrooms/new
  # GET /classrooms/new.json
  def new
    @classroom = Classroom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classroom }
    end
  end

  # GET /classrooms/1/edit
  def edit
    @classroom = Classroom.find(params[:id])
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(params[:classroom])

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render json: @classroom, status: :created, location: @classroom }
      else
        format.html { render action: "new" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classrooms/1
  # PUT /classrooms/1.json
  def update
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      if @classroom.update_attributes(params[:classroom])
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end
end

project1_schedule/schedule_app/app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

project1_schedule/schedule_app/app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :maxpeople %><br />
    <%= f.number_field :maxpeople %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project1_schedule/schedule_app/app/views/classrooms/edit.html.erb
<h2>Editing classroom</h2>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', classrooms_path %>

project1_schedule/schedule_app/app/views/classrooms/index.html.erb
<h2>Listing classrooms</h2>

<div class = "classrooms">
<table>
  <tr>
    <td>Name</td>
    <td>Maxpeople</td>
    <td>Course</td>
  </tr>

<% @classrooms.each do |classroom| %>
  <tr>
    <td><%= link_to classroom.name, classroom %></td>
    <td><%= classroom.maxpeople %></td>
    <td><% classroom.courses.each do |course|%>
        <%= course.name %>, 
        <% end %>

      </td>  
  </tr>
<% end %>
</table>
</div>
<br />

<div class = "actions">
  <%= link_to 'New Classroom', new_classroom_path %>
</div>

project1_schedule/schedule_app/app/views/classrooms/new.html.erb
<h2>New classroom</h2>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

project1_schedule/schedule_app/app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Classroom Information</h3>


<div class = "classroom_show">
<p>
  <b>Name:</b>
  <%= @classroom.name %>
</p>

<p>
  <b>Maxpeople:</b>
  <%= @classroom.maxpeople %>
</p>

<p>
<b>Courses held in Classroom: </b>
  <% @classroom.courses.each do | course |%>
  <%= course.name%>
  <%end%>
</p>
</div>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Destroy', classroom_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', classrooms_path %>