project1_schedule/schedule_app/config/routes.rb
ScheduleApp::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :sessions
  get "/logout", to: "sessions#destroy"
  
  resources :users do 
    collection {post :search, to: 'users#search'}
  end 

  resources :courses

  resources :classrooms

  resources :locations
  

  get "/events/:id", to: "courses#show"

   
  
  root :to => 'locations#index'

end

project1_schedule/schedule_app/app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name

  has_many :courses, through: :classroom
  has_many :classroom
end

project1_schedule/schedule_app/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  authorize_resource
  skip_authorize_resource only: :index
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    @running_courses = Course.running_courses
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

project1_schedule/schedule_app/app/helpers/locations_helper.rb
module LocationsHelper
end

project1_schedule/schedule_app/app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project1_schedule/schedule_app/app/views/locations/edit.html.erb
<h2>Editing location</h2>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

project1_schedule/schedule_app/app/views/locations/index.html.erb
<h2>WELCOME TO THE GENERAL ASSEMBLY SCHEDULER</h2>

  <div class = "intro">
    <p>Here at GA we look at running a smooth and efficient teaching experience, hence why we have hired the best developer to produce this smart website. Login below to view class schedule:</p>
  </div>


  <div class="sign_up">
      <%=image_tag("ga_big_red_logo.png")%>
    
    <%= form_tag sessions_path do %>
      <div class="field">
        <%= label_tag :email %>
        <%= text_field_tag :email, params[:email] %>
      </div><br>
      <div class="field">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div><br>
      <div class="actions"><%= submit_tag "Log in" %></div>
    <% end %>
  </div>

project1_schedule/schedule_app/app/views/locations/new.html.erb
<h2>New location</h2>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

project1_schedule/schedule_app/app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Current Classes on at <span>GA</span></h2>

<h3> We currently have the following classes in session on at <%= @location.name %>:</h3>
 
  
<div class= "classroombox">
  <% @running_courses.each do |running_course|%>

    <div class="classroom" >
      
      <p>
        <b>Name:</b>
          <%=link_to running_course.name, running_course %>
      </p>
      
      <p>
        <b>Maxsize:</b>
        <%= running_course.maxsize %>
      </p>
      
      <p>
        <b>Head Teacher:</b>
        <% running_course.instructors.each do |instructors|%>
              <%= instructors.name %>
              <% end %>
      </p>
      
      <p>
        <b>Teaching Assitants:</b>
        <% running_course.teaching_assistants.each do |teaching_assistants|%>
              <%= teaching_assistants.name %>, 
              <% end %>
      </p>
      
      <p>
        <b>Students:</b>
        <% running_course.students.each do |students|%>
              <%= students.name %>, 
              <% end %>
      </p>
    </div>
  <% end %>
</div>
<br>
<h3>Please remember to swing your moods as well. Tell us how the class is going...<a href="http://ga-moodswings.herokuapp.com/" target="_blank">GA mood swing</a></h3>