project1_schedule/schedule_app/config/routes.rb
ScheduleApp::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :sessions
  get "/logout", to: "sessions#destroy"
  
  resources :users do 
    collection {post :search, to: 'users#search'}
  end 

  resources :courses

  resources :classrooms

  resources :locations
  

  get "/events/:id", to: "courses#show"

   
  
  root :to => 'locations#index'

end

project1_schedule/schedule_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScheduleApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'ga_big_red_logo.ico' %>
  <link href='http://fonts.googleapis.com/css?family=Fauna+One' rel='stylesheet' type='text/css'>
</head>
<body>
  <header class="header">

    <a href="http://localhost:3000/locations/1"><%=image_tag("red_logo.png")%>
    <h1>GENERAL ASSEMBLY SCHEDULER </h1></a>
    
    <nav>
      <%= link_to "Courses", courses_path %> 
      <%= link_to "Classrooms", classrooms_path %> 
      <%= link_to "Users", users_path %>
      <%= link_to "Calendar", calendar_path %> 
    </nav>
      <div class="login"> 
        <% if current_user %>
          <%= current_user.name%>
          <%= link_to "Logout", logout_path %>
        <%else%>
          <%= link_to "Login", new_session_path %> or <%= link_to "Signup", new_user_path %>
        <% end %>
      </div>
    
  </header>
    
  <div class = "time">
    Current Time: <%= Time.now.strftime("%H:%M") %>
  </div>


   <% flash.each do |name, msg| %>
      <div class="flash-message flash-message-<%= name %>">
        <%= msg %>
      </div>
    <% end %>

  <div class = "main"> 
    <%= yield %>
  </div>


<footer>
  <div class = "contact">
    <p>
    Contact Us: <br>
     
    9 Back Hill, 4th Floor <br>
    London EC1R 5EN <br>
    United Kingdom <br>
    +44 (0) 7850 456 607 <br>
    london@generalassemb.ly.
  </div>

<div class = "social">
  <a href="http://www.facebook.com/gnrlassembly" target="_blank" title="Visit General Assembly on Facebook">
  <img alt="GA on Facebook" class="square-social-icons" src="https://ga-core-production-herokuapp-com.global.ssl.fastly.net/assets/square-social-icons/icon-facebook-32x32-999aec86e2d51ad3337036415b274a3e.png">
  </a>
  <a href="https://twitter.com/ga" target="_blank" title="Follow @GA on Twitter">
  <img alt="GA on Twitter" class="square-social-icons" src="https://ga-core-production-herokuapp-com.global.ssl.fastly.net/assets/square-social-icons/icon-twitter-32x32-717e4ee3df39e32e5d8e64535448f41d.png">
  </a>
  <a href="http://www.linkedin.com/company/2408664" target="_blank" title="Network with General Assembly on LinkedIn">
  <img alt="GA on LinkedIn" class="square-social-icons" src="https://ga-core-production-herokuapp-com.global.ssl.fastly.net/assets/square-social-icons/icon-linkedin-32x32-8b4842ecfd266b1647680251435604ad.png">
  </a>
  <a href="http://instagram.com/generalassembly" target="_blank" title="See what’s happening on GA’s Instagram.">
  <img alt="GA on Instagram" class="square-social-icons" src="https://ga-core-production-herokuapp-com.global.ssl.fastly.net/assets/square-social-icons/icon-instagram-32x32-fbd3cb1f8f998684120881d70f9ff9cb.png">
  </a>
  <a href="https://plus.google.com/+GeneralAssembly" rel="publisher" target="_blank" title="Visit General Assembly on Google Plus">
  <img alt="GA on Google Plus" class="square-social-icons" src="https://ga-core-production-herokuapp-com.global.ssl.fastly.net/assets/square-social-icons/icon-googleplus-32x32-4962b432a6d1f0148a770ac1f4a424a0.png">
  </a>

</div>




</footer>

</body>


</html>